[package]
name = "ahrs-fusion"
version = "0.1.0"
edition = "2021"
description = "Port of NXP Sensor Fusion (as written by Adafruit)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "*"

[build-dependencies]
cc = "*"
bindgen = "*"
